# Generated by Django 5.2.5 on 2026-06-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='profile_pic',
            field=models.ImageField(default='defaults/default_profile.png', upload_to='profile_pics/'),
        ),
    ]
