# Generated by Django 5.2.5 on 2026-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trainerprofile_is_active_alter_trainerprofile_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='is_fired',
            field=models.BooleanField(default=False),
        ),
    ]
