# Generated by Django 5.2.5 on 2026-06-15 12:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='cario', max_length=100, unique=True)),
                ('city', models.CharField(choices=[('tanta', 'Tanta'), ('cairo', 'Cairo'), ('alexandria', 'Alexandria'), ('mansura', 'Mansura'), ('suez', 'Suez'), ('north_sinai', 'North_Sinai'), ('boston', 'Boston'), ('london', 'London'), ('berlin', 'Berlin'), ('barcelona', 'Barcelona'), ('moscow', 'Moscow'), ('stockholm', 'Stockholm')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('visa', 'Visa'), ('wallet', 'Wallet')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('paused', 'Paused')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShipUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('spa_sessions_used', models.PositiveIntegerField(default=0)),
                ('suana_sessions_used', models.PositiveIntegerField(default=0)),
                ('jacuzzi_sessions_used', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('500.0'))])),
                ('duration', models.CharField(choices=[('one_month', 'One_Month'), ('three_months', 'Three_Months'), ('six_months', 'Six_Months'), ('twelve_months', 'Twelve_Months')], default='one_month', max_length=20)),
                ('number_of_sessions', models.PositiveIntegerField(default=10)),
                ('number_of_spa_sessions', models.PositiveIntegerField(default=0)),
                ('number_of_suana_sessions', models.PositiveIntegerField(default=0)),
                ('number_of_jacuzzi_sessions', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
